type: "joint_state_controller/JointStateController"
publish_rate: 50

body_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - body_roll_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

head_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_tilt_joint
    - head_pan_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

r_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_arm_shoulder_roll_joint
    - r_arm_shoulder_pan_joint
    - r_arm_elbow_tilt_joint
    - r_arm_wrist_tilt_joint
    - r_hand_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

l_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_arm_shoulder_roll_joint
    - l_arm_shoulder_pan_joint
    - l_arm_elbow_tilt_joint
    - l_arm_wrist_tilt_joint
    - l_hand_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true


gazebo_ros_control:
  pid_gains:
    l_arm_shoulder_roll_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    l_arm_shoulder_pan_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    l_arm_elbow_tilt_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    l_arm_wrist_tilt_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    l_hand_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}

    r_arm_shoulder_roll_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    r_arm_shoulder_pan_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    r_arm_elbow_tilt_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    r_arm_wrist_tilt_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    r_hand_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}

    # body_roll_joint: {p: 0.1, i: 0.5, d: 0.0, i_clamp: 1.0}
    # body_big_gear_base_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}

    head_tilt_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
    head_pan_joint: {p: 200, i: 0.1, d: 0.3, i_clamp: 1.0}
